# -------------------------------------------------------------------------
# MAPCAP ECOSYSTEM - AUTOMATED QUALITY ASSURANCE (QA) PIPELINE v1.7.5 (TS)
# -------------------------------------------------------------------------
# Architecture Lead: EslaM-X | AppDev @Map-of-Pi
# Project: MapCap Ecosystem | Spec: Continuous Integration for Web3 Solutions
# -------------------------------------------------------------------------
# UPDATES:
# - Added TypeScript Compilation (Build) step prior to testing.
# - Maintained matrix for Node 18.x and 20.x for runtime stability.
# - Preserved all secure environment variables for Daniel's compliance.
# -------------------------------------------------------------------------

name: MapCap Quality Assurance

on:
  push:
    branches: [ main, develop, dev ] 
  pull_request:
    branches: [ main, develop ]

jobs:
  build-and-test:
    name: Build & Validate Ecosystem
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x]

    steps:
      # STEP 1: REPOSITORY SYNCHRONIZATION
      - name: Checkout Source Code from Repository
        uses: actions/checkout@v3

      # STEP 2: ENVIRONMENT PROVISIONING
      - name: Initialize Node.js ${{ matrix.node-version }} Environment
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      # STEP 3: DEPENDENCY RESOLUTION
      - name: Install Project Dependencies
        run: npm install

      # STEP 4: TYPESCRIPT COMPILATION (CRITICAL FOR TS)
      # Ensures that all .ts files are syntactically correct and compile 
      # successfully before running any logic tests.
      - name: Compile TypeScript (Production Build)
        run: npm run build
        if: success()

      # STEP 5: FULL-STACK INTEGRATION TESTING
      # Orchestrates the complete test suite including Price Discovery, 
      # Payout Pipelines, and Admin Security Gates.
      - name: Execute Unified Test Suite (Unit & Integration)
        run: npm test
        if: success()
        env:
          NODE_ENV: test
          # SENSITIVE DATA INJECTION:
          # Securely fetching secrets from GitHub Action Secrets.
          MONGO_URI_TEST: ${{ secrets.MONGO_URI_TEST }}
          JWT_SECRET: ${{ secrets.JWT_SECRET }}
          ADMIN_SECRET_TOKEN: ${{ secrets.ADMIN_SECRET_TOKEN }}
          PI_API_KEY: ${{ secrets.PI_API_KEY }}
