# -------------------------------------------------------------------------
# MAPCAP ECOSYSTEM - AUTOMATED QUALITY ASSURANCE (QA) PIPELINE
# -------------------------------------------------------------------------
# Architecture Lead: EslaM-X | AppDev @Map-of-Pi
# Version: 1.1.0 (Stabilized for Termux & MERN Integration)
# Documentation: Validates architectural integrity, financial ledger logic, 
# and security gateways across multiple Node.js runtimes.
# -------------------------------------------------------------------------

name: MapCap Quality Assurance

# TRIGGER SPECIFICATIONS:
# Ensures code integrity on every core branch update and Pull Request.
on:
  push:
    branches: [ main, develop, dev ] 
  pull_request:
    branches: [ main, develop ]

jobs:
  build-and-test:
    name: Build & Validate Ecosystem
    runs-on: ubuntu-latest

    # COMPATIBILITY MATRIX:
    # Testing against current LTS and stable Node.js versions for environment parity.
    strategy:
      matrix:
        node-version: [18.x, 20.x]

    steps:
      # STEP 1: REPOSITORY SYNCHRONIZATION
      - name: Checkout Source Code from Repository
        uses: actions/checkout@v3

      # STEP 2: ENVIRONMENT PROVISIONING
      - name: Initialize Node.js ${{ matrix.node-version }} Environment
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm' # Optimized for faster subsequent runs via dependency caching

      # STEP 3: DEPENDENCY RESOLUTION
      - name: Install Project Dependencies (Clean Install)
        run: npm install

      # STEP 4: FULL-STACK INTEGRATION TESTING
      # Orchestrates the complete test suite including Price Discovery, 
      # Payout Pipelines, and Admin Security Gates.
      - name: Execute Unified Test Suite (Unit & Integration)
        run: npm test
        env:
          NODE_ENV: test
          # SENSITIVE DATA INJECTION:
          # Securely fetching secrets from GitHub Action Secrets to maintain 
          # environment parity without exposing credentials in the codebase.
          MONGO_URI_TEST: ${{ secrets.MONGO_URI_TEST }}
          JWT_SECRET: ${{ secrets.JWT_SECRET }}
          # AUTHENTICATION GATEWAY:
          # Required for passing v1.5.4 Admin RBAC Middleware checks.
          ADMIN_SECRET_TOKEN: ${{ secrets.ADMIN_SECRET_TOKEN }}
